{
 "title": "Apache-storm",
 "time": { "from": "now-12h", "to": "now" },
 "refresh": "5s",
 "panels": [
  { "title": "Cluster", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Total worker process",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    { "expr": "worker_cluster_total", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Worker process have used",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    { "expr": "worker_cluster_used", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Supervisors",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    { "expr": "supervisor_cluster_total", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Weight_scale",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "targets": [
    { "expr": "weight_scale", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Topology",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 },
   "collapsed": true,
   "panels": [
    {
     "title": "Mem on heap",
     "type": "timeseries",
     "description": "Requested On-Heap Memory by User",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
     "fieldConfig": { "defaults": { "unit": "decmbytes" } },
     "targets": [
      { "expr": "requested_mem_on_heap", "legendFormat": "__auto" }
     ]
    },
    {
     "title": "Total mem",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
     "fieldConfig": { "defaults": { "unit": "decmbytes" } },
     "targets": [
      { "expr": "requested_total_mem", "legendFormat": "__auto" }
     ]
    },
    {
     "title": "Total executors",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
     "targets": [
      { "expr": "executors_total", "legendFormat": "__auto" }
     ]
    },
    {
     "title": "Total tasks",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 25 },
     "targets": [
      { "expr": "tasks_total", "legendFormat": "__auto" }
     ]
    },
    {
     "title": "Total workers",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 33 },
     "targets": [
      { "expr": "workers_total", "legendFormat": "__auto" }
     ]
    },
    {
     "title": "Data Emitted",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 33 },
     "targets": [
      {
       "expr": "topology_stats_emitted{window=\"600\"}",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Process latency",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 41 },
     "targets": [
      {
       "expr": "topology_stats_complete_latency{window=\"600\"}",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Request CPU",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 41 },
     "targets": [
      { "expr": "requested_cpu", "legendFormat": "__auto" }
     ]
    },
    {
     "title": "Data transfer",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 49 },
     "targets": [
      {
       "expr": "topology_stats_trasferred{window=\"600\"}",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "Bolts",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 },
   "collapsed": true,
   "panels": [
    {
     "title": "Bolt emitted",
     "type": "timeseries",
     "description": "Num of tuples emitted by the bolt",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
     "targets": [
      { "expr": "bolts_emitted", "legendFormat": "__auto" }
     ]
    },
    {
     "title": "Bolt Ack",
     "type": "timeseries",
     "description": "Number of tuples acked by the bolt",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
     "targets": [
      { "expr": "bolts_acked", "legendFormat": "__auto" }
     ]
    },
    {
     "title": "Bolt ACK failed",
     "type": "timeseries",
     "description": "Number of tuples failed by the bolt",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
     "targets": [
      { "expr": "bolts_failed", "legendFormat": "__auto" }
     ]
    },
    {
     "title": "Bolt capacity",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 26 },
     "targets": [
      { "expr": "bolts_capacity", "legendFormat": "__auto" }
     ]
    },
    {
     "title": "Bolt tasks",
     "type": "timeseries",
     "description": "Number of instances of bolt",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 34 },
     "targets": [
      { "expr": "bolts_tasks", "legendFormat": "__auto" }
     ]
    },
    {
     "title": "Bolt executors",
     "type": "timeseries",
     "description": "bolts_executors Number of executor tasks in the bolt component",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 34 },
     "targets": [
      { "expr": "bolts_executors", "legendFormat": "__auto" }
     ]
    },
    {
     "title": "Bolt execute latency",
     "type": "timeseries",
     "description": "bolts_execute_latency Average time to run the execute method of the bolt",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 42 },
     "targets": [
      { "expr": "bolts_execute_latency", "legendFormat": "__auto" }
     ]
    },
    {
     "title": "Bolt process latency",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 42 },
     "targets": [
      { "expr": "bolts_process_latency", "legendFormat": "__auto" }
     ]
    }
   ]
  },
  {
   "title": "Spouts",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 },
   "collapsed": true,
   "panels": [
    {
     "title": "Spout executors",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 19 },
     "targets": [
      { "expr": "spouts_executors", "legendFormat": "__auto" }
     ]
    },
    {
     "title": "Spout tasks",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 19 },
     "targets": [
      { "expr": "spouts_tasks", "legendFormat": "__auto" }
     ]
    },
    {
     "title": "Spout transferred",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 27 },
     "targets": [
      { "expr": "spouts_transferred", "legendFormat": "__auto" }
     ]
    },
    {
     "title": "Spout ack",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 27 },
     "targets": [
      { "expr": "spouts_acked", "legendFormat": "__auto" }
     ]
    },
    {
     "title": "Spout failed",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 35 },
     "targets": [
      { "expr": "spouts_failed", "legendFormat": "__auto" }
     ]
    },
    {
     "title": "Spout emit",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 35 },
     "targets": [
      { "expr": "spouts_emitted", "legendFormat": "__auto" }
     ]
    },
    {
     "title": "Spout complete latency",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 43 },
     "targets": [
      { "expr": "spouts_complete_latency", "legendFormat": "__auto" }
     ]
    }
   ]
  }
 ]
}