services:
  zookeeper:
    image: zookeeper
    container_name: zookeeper
    networks:
      storm_network:
    volumes:
      - ./config/zoo.cfg:/apache-zookeeper-3.9.2-bin/conf/zoo.cfg


  nimbus:
    image: storm
    container_name: nimbus
    command: sh -c "storm nimbus & storm ui"
    volumes:
      - ./config/storm-nimbus.yaml:/conf/storm.yaml
      - ./storm-src/target/storm-src-1.0-SNAPSHOT.jar:/opt/storm/lib/storm-autoscale-1.0.jar
      - ./storm-src/target/Storm-IOTdata-1.0-SNAPSHOT-jar-with-dependencies.jar:/opt/storm/lib/Storm-IOTdata-1.0.jar
    ports:
      - 8081:8081
    networks:
      storm_network:

  supervisor:
    image: storm
    container_name: supervisor
    command: storm supervisor
    volumes:
      - ./config/storm-supervisor.yaml:/conf/storm.yaml
    networks:
      storm_network:

  supervisor2:
    image: storm
    container_name: supervisor2
    command: storm supervisor
    volumes:
      - ./config/storm-supervisor.yaml:/conf/storm.yaml
    networks:
      storm_network:

  mqtt-broker:
    image: mr4x2/mqtt-broker-iotdata:v1
    container_name: mqtt-broker
    networks:
      storm_network:
    ports:
      - 1883:1883
  
  mysql:
    image: mysql:8.4.2
    command: --mysql-native-password=ON
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: Uet123
      MYSQL_DATABASE: iotdata
      MYSQL_USER: user1
      MYSQL_PASSWORD: Uet123
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      storm_network:

  storm-exporter:
    image: mr4x2/stormexporter:v1.2.6
    container_name: storm-exporter
    environment:
      - STORM_UI_HOST=nimbus:8081
      - PORT_EXPOSE=8082
      - REFRESH_RATE=5
    networks:
      storm_network:
    ports:
      - 8082:8082
    depends_on:
      - nimbus
    # TODO: update health check with depend on to avoid fail in run container

# TODO: add log with fluentd to get log from supervisor

networks:
  storm_network:
    driver: bridge

volumes:
  mysql_data:
