kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
networking:
  # WARNING: It is _strongly_ recommended that you keep this the default
  # (127.0.0.1) for security reasons. However it is possible to change this.
  apiServerAddress: "127.0.0.1" # use ip public to allow connect from outside
  # By default the API server listens on a random open port.
  # You may choose a specific port but probably don't need to in most cases.
  # Using a random port makes it easier to spin up multiple clusters.
  apiServerPort: 6443
nodes:
- role: control-plane
  extraPortMappings:
  - containerPort: 30001
    hostPort: 30001
    listenAddress: "0.0.0.0" # Optional, defaults to "0.0.0.0"
  - containerPort: 30002
    hostPort: 30002
    listenAddress: "0.0.0.0"
  - containerPort: 30003
    hostPort: 30003
    listenAddress: "0.0.0.0"
  - containerPort: 30004
    hostPort: 30004
    listenAddress: "0.0.0.0" # Optional, defaults to "0.0.0.0"
  - containerPort: 30005
    hostPort: 30005
    listenAddress: "0.0.0.0"
  - containerPort: 30006
    hostPort: 30006
    listenAddress: "0.0.0.0"
- role: worker
- role: worker